### ISSUE TITLE
Endpoint (-s) to return size and resolution

### ISSUE THREAD

**Issue by vvgordeev** [ringfence-inc/ringfence-client-web#59]
- [x]  Return resolution of an image (width and height as a separate strings)
- [x]  Return size of an image
- [x]  Return size of all images in a collection (collection total size)
- [x]  Return total size of all user files
- [x] Calculate size for all collections

**Comment by vvgordeev** [comment]
Additional data for an image was requested:
- seed
- guidance scale
- prompt

**Comment by vvgordeev** [comment]
Calculating size of a collection we should consider all images - even copies - as original and having size.

**Comment by vvgordeev** [comment]
@volodymyrkostenko 
Any (virtual) copy of an image in terms of image size display and calculation should be treated as having size of an original image. So, all copies:
- Should be displayed via API as having size
- Should be calculated as having size for purposes of collection size caclulation
- Should be calculated as having size for purposes of all-user-images size calculation (all-collections size calculation)
-

**Comment by vvgordeev** [comment]
Need same metadata for all generated images

**Comment by vvgordeev** [comment]
All copies of any image should be counted as separate images:

for purposes of displaying single image size
for collections size calculation
for all user storage space calculation.

**Comment by vvgordeev** [comment]
And still no prompt, guidance and seed in generated images

**Comment by vvgordeev** [comment]
**No size in collections**
![Image](https://github.com/ringfence-inc/ringfence-client-web/assets/38768777/8b88771c-2d92-412e-93eb-eb13c7e5d1c0)

**Comment by volodymyrkostenko** [comment]
@vvgordeev it is fine now

https://github.com/ringfence-inc/ringfence-client-web/assets/13867047/bf23a13f-9c6e-4172-ab45-c266e8de847f
