### ISSUE TITLE
Add function to exclude collection for get-images endpoint

### ISSUE THREAD

**Issue by vvgordeev** [ringfence-inc/ringfence-client-web#62]
Have to add filter that excludes images of a collection with certain ID.

**Comment by volodymyrkostenko** [comment]
@vvgordeev 
There should be a field, like `exclude_collection_id`, that accepts a numeric parameter, and I should retrieve all images except those from this collection.
Is this correct?

If yes, I guess it will be a good idea that you cannot pass two fields: `collection_id` and `exclude_collection_id` in one query.

**Comment by vvgordeev** [comment]
@volodymyrkostenko 
Yes, all is totally correct!
